apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-quota
  namespace: lab
spec:
  hard:
    pods: "50"

    requests.cpu: "4"
    limits.cpu: "8"

    requests.memory: 8Gi
    limits.memory: 16Gi
